{% set name = "uncalled" %}
{% set version = "0.1.8" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uncalled-{{ version }}.tar.gz
  sha256: b74ef3aa63982f5ddedae2b1670e5a72d2cd1cd9d04f9a4896063771ae6f3ddb

build:
  entry_points:
    - uncalled = uncalled.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ={{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - uncalled
  commands:
    - pip check
    - uncalled --help
  requires:
    - pip
    - python ={{ python_min }}

about:
  home: https://github.com/elazarg/uncalled
  summary: Find unused functions in Python projects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
